objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Log__c/fields/Custom_App__c.field-meta.xml
<CustomField>
    <fullName>Custom_App__c</fullName>
    <label>Custom App</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>MATRIX</fullName>
            </value>
            <value>
                <fullName>HERMES</fullName>
            </value>
            <value>
                <fullName>MELISSA</fullName>
            </value>
            <value>
                <fullName>PARTNER</fullName>
            </value>
            <value>
                <fullName>SERVICEPOWER</fullName>
            </value>
            <value>
                <fullName>FLEXFI</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>ALN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log__c/fields/Save_Mode__c.field-meta.xml
<CustomField>
    <fullName>Save_Mode__c</fullName>
    <label>Save Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALWAYS</fullName>
            </value>
            <value>
                <fullName>FLAG_BASED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOW</fullName>
            </value>
            <value>
                <fullName>MEDIUM</fullName>
            </value>
            <value>
                <fullName>HIGH</fullName>
            </value>
            <value>
                <fullName>CRITICAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

objects/Log_Event__e/fields/Custom_App__c.field-meta.xml
<CustomField>
    <fullName>Custom_App__c</fullName>
    <label>Custom App</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log_Event__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/Save_Mode__c.field-meta.xml
<CustomField>
    <fullName>Save_Mode__c</fullName>
    <label>Save Mode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/LogEventTriggerHelperTest.cls
@IsTest
public with sharing class LogEventTriggerHelperTest {
    static testMethod void logSeverityCriticalTest(){
        Test.startTest();
        try {
            insert new Contact();
        } catch (DmlException ex){
            CustomHandledException customEx = new CustomHandledException(ex, 'Test Dml Exception');

            Log_Event__e event = new Log_Event__e();
            event.Severity__c = Log.SEVERITY.CRITICAL.name();
            event.Save_Mode__c = Log.SAVE_MODE.ALWAYS.name();
            event.Custom_App__c = Log.CUSTOM_APP.STANDARD.name();
            event.User_Id__c = UserInfo.getUserId();
            event.Exception__c = customEx.getMessage();
            event.Exception_Type__c = customEx.getTypeName();
            Database.SaveResult saveResult = Eventbus.publish(event);
            System.assertEquals(True, saveResult.isSuccess(), 'Event not published');
            //List<Log__c> logs = [SELECT Id FROM Log__c];
            //System.assertEquals(1, logs.size(), 'Incorrect number of logs created');
        }
        Test.stopTest();
    }
}