objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Log__c/fields/Custom_App__c.field-meta.xml
<CustomField>
    <fullName>Custom_App__c</fullName>
    <label>Custom App</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>MATRIX</fullName>
            </value>
            <value>
                <fullName>HERMES</fullName>
            </value>
            <value>
                <fullName>MELISSA</fullName>
            </value>
            <value>
                <fullName>PARTNER</fullName>
            </value>
            <value>
                <fullName>SERVICEPOWER</fullName>
            </value>
            <value>
                <fullName>FLEXFI</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>ALN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log__c/fields/Save_Mode__c.field-meta.xml
<CustomField>
    <fullName>Save_Mode__c</fullName>
    <label>Save Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALWAYS</fullName>
            </value>
            <value>
                <fullName>FLAG_BASED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LOW</fullName>
            </value>
            <value>
                <fullName>MEDIUM</fullName>
            </value>
            <value>
                <fullName>HIGH</fullName>
            </value>
            <value>
                <fullName>CRITICAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

objects/Log_Event__e/fields/Custom_App__c.field-meta.xml
<CustomField>
    <fullName>Custom_App__c</fullName>
    <label>Custom App</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log_Event__e/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Log_Event__e/fields/Save_Mode__c.field-meta.xml
<CustomField>
    <fullName>Save_Mode__c</fullName>
    <label>Save Mode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Log_Event__e/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/LogEventTriggerHelper.cls
public with sharing class LogEventTriggerHelper {
    public static void insertLogs(List<Log_Event__e> events) {
        insert new Account(Name='T');
        [SELECT COUNT() FROM Account WHERE Name = 'TEST']
    //     List<Log__c> logs = new List<Log__c>();
    //     for (Log_Event__e event : events) {
    //         Log__c log = new Log__c();
    //         log.Severity__c = event.Severity__c;
    //         log.Save_Mode__c = event.Save_Mode__c;
    //         log.Custom_App__c = event.Custom_App__c;
    
    //         log.User__c = event.User_Id__c;
    //         log.Exception__c = event.Exception__c;
    //         log.Exception_Type__c = event.Exception_Type__c;
    //         log.Message__c = event.Message__c;
    //         logs.add(log);
    //     }

    //     insert logs;

    //     for(Log__c logRecord : logs){
    //         Boolean isCriticalLog = logRecord.Severity__c == Log.SEVERITY.CRITICAL.name();
    //         if(isCriticalLog){
    //             sendEmail(logRecord);
    //         }
    //     }
    }

    // private static void sendEmail(Log__c log){
    //     System.debug('@@@ Sending email as critical log was reported: ' + log);
    // }
}